using System.Text.Json;

namespace PortalCraft.RepoTool;

public sealed class IntegrationGenerator
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
    };

    public GenerationResult Generate(
        RepositoryProfile profile,
        string outputDirectory,
        bool force = false)
    {
        var output = Path.GetFullPath(outputDirectory);
        if (Directory.Exists(output)
            && Directory.EnumerateFileSystemEntries(output).Any()
            && !force)
        {
            throw new InvalidOperationException(
                $"Output directory is not empty: {output}. Pass --force to replace generated files.");
        }

        Directory.CreateDirectory(output);
        var files = new List<string>();
        Write(
            output,
            "portalcraft-ai.manifest.json",
            JsonSerializer.Serialize(profile, JsonOptions),
            files);
        Write(output, "server/PortalCraftGeneratedCatalog.cs", BuildServerCatalog(profile), files);
        Write(output, "client/portalCraft.generated.ts", BuildClientCatalog(profile), files);
        Write(output, "client/PortalCraftGeneratedPanel.tsx", BuildClientPanel(), files);
        Write(output, "dashboard/index.html", BuildDashboard(profile), files);
        Write(output, "README.md", BuildReadme(profile), files);
        return new(profile, output, files);
    }

    private static void Write(
        string output,
        string relativePath,
        string content,
        ICollection<string> files)
    {
        var path = Path.Combine(output, relativePath.Replace('/', Path.DirectorySeparatorChar));
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, content);
        files.Add(path);
    }

    private static string BuildServerCatalog(RepositoryProfile profile)
    {
        var queries = string.Join(
            $",{Environment.NewLine}",
            profile.QueryCandidates.Select(candidate =>
                $"        new(\"{Escape(candidate.Id)}\", \"{Escape(candidate.Prompt)}\", " +
                $"\"{Escape(candidate.OperationId)}\", {NullableString(candidate.ViewPath)})"));

        return $$"""
            // Generated by PortalCraft.RepoTool. Review before integrating.
            using Microsoft.AspNetCore.Builder;
            using Microsoft.AspNetCore.Http;
            using Microsoft.AspNetCore.Routing;

            namespace PortalCraft.Generated;

            public sealed record PortalCraftGeneratedQuery(
                string Id,
                string Prompt,
                string OperationId,
                string? ViewPath);

            public static class PortalCraftGeneratedCatalog
            {
                public static readonly IReadOnlyList<PortalCraftGeneratedQuery> Queries =
                [
            {{queries}}
                ];

                public static IEndpointRouteBuilder MapPortalCraftGeneratedCatalog(
                    this IEndpointRouteBuilder endpoints)
                {
                    endpoints.MapGet("/api/portalcraft-ai/catalog", () => Results.Ok(Queries));
                    return endpoints;
                }
            }
            """;
    }

    private static string BuildClientCatalog(RepositoryProfile profile) =>
        $$"""
        // Generated by PortalCraft.RepoTool. Review before integrating.
        export type PortalCraftGeneratedQuery = {
          id: string;
          prompt: string;
          operationId: string;
          viewPath?: string;
        };

        export const portalCraftGeneratedQueries = {{JsonSerializer.Serialize(profile.QueryCandidates, JsonOptions)}} as const;
        """;

    private static string BuildClientPanel() =>
        """
        import { portalCraftGeneratedQueries } from "./portalCraft.generated";

        type Props = {
          assistantName?: string;
          onAsk: (prompt: string) => void;
        };

        export function PortalCraftGeneratedPanel({
          assistantName = "PortalCraft AI",
          onAsk,
        }: Props) {
          return (
            <aside aria-label={assistantName}>
              <h2>{assistantName}</h2>
              <p>Repository-discovered, read-only query starters</p>
              <div>
                {portalCraftGeneratedQueries.map(query => (
                  <button key={query.id} type="button" onClick={() => onAsk(query.prompt)}>
                    {query.prompt}
                  </button>
                ))}
              </div>
            </aside>
          );
        }
        """;

    private static string BuildReadme(RepositoryProfile profile) =>
        $$"""
        # Generated PortalCraft AI onboarding

        The repository tool discovered:

        - {{profile.ApiOperations.Count}} API operations
        - {{profile.ApiOperations.Count(operation => operation.ReadOnly)}} read-only API operations
        - {{profile.UiRoutes.Count}} UI routes
        - {{profile.QueryCandidates.Count}} query candidates

        ## Integration

        1. Review `portalcraft-ai.manifest.json`; remove false positives and add product-owned authorization requirements.
        2. Copy `server/PortalCraftGeneratedCatalog.cs` into the ASP.NET Core project and call
           `app.MapPortalCraftGeneratedCatalog()`.
        3. Copy the generated client files into the React application.
        4. Connect `onAsk` to the product's governed PortalCraft AI chat endpoint.
        5. Implement typed handlers for approved operations. The generator never exposes write operations automatically.

        Generated files are scaffolding, not an authorization boundary. Product APIs must continue to enforce
        authentication, authorization, validation, audit, and data classification.

        ## Preview

        From the PortalCraft AI source repository:

        `dotnet run --project tools/PortalCraft.RepoTool -- serve "{{profile.Repository}}/.portalcraft-ai"`
        """;

    private static string BuildDashboard(RepositoryProfile profile)
    {
        var data = JsonSerializer.Serialize(profile, JsonOptions)
            .Replace("</", "<\\/", StringComparison.Ordinal);
        return $$"""
        <!doctype html>
        <html lang="en">
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <title>PortalCraft AI repository dashboard</title>
          <style>
            :root { font-family: Segoe UI, Arial, sans-serif; color: #172033; background: #eef3f8; }
            body { margin: 0; }
            header { padding: 22px 30px; color: white; background: #172033; }
            header h1 { margin: 0 0 5px; }
            header p { margin: 0; color: #c9d6e5; }
            main { padding: 26px 30px 50px; }
            .metrics { display: grid; grid-template-columns: repeat(4, minmax(150px, 1fr)); gap: 14px; }
            .card, section { border: 1px solid #d7dee8; border-radius: 12px; background: white; box-shadow: 0 3px 12px #1720330d; }
            .card { padding: 18px; }
            .card span { display: block; color: #5b6879; font-size: 13px; }
            .card strong { display: block; margin-top: 8px; font-size: 30px; }
            section { margin-top: 20px; padding: 20px; overflow-x: auto; }
            h2 { margin: 0 0 15px; }
            table { width: 100%; border-collapse: collapse; font-size: 13px; }
            th, td { padding: 10px; border-bottom: 1px solid #edf1f5; text-align: left; vertical-align: top; }
            th { color: #526173; }
            code { color: #005a9e; }
            .safe { color: #107c10; font-weight: 700; }
            .blocked { color: #a4262c; font-weight: 700; }
            @media (max-width: 800px) { .metrics { grid-template-columns: repeat(2, 1fr); } main { padding: 18px; } }
          </style>
        </head>
        <body>
          <header>
            <h1>PortalCraft AI repository dashboard</h1>
            <p id="repository"></p>
          </header>
          <main>
            <div class="metrics" id="metrics"></div>
            <section>
              <h2>Suggested read-only queries</h2>
              <table><thead><tr><th>Prompt</th><th>Operation</th><th>View</th><th>Parameters</th></tr></thead><tbody id="queries"></tbody></table>
            </section>
            <section>
              <h2>Discovered API operations</h2>
              <table><thead><tr><th>Method</th><th>Route</th><th>Classification</th><th>Source</th></tr></thead><tbody id="operations"></tbody></table>
            </section>
            <section>
              <h2>Discovered UI routes</h2>
              <table><thead><tr><th>Route</th><th>Source</th></tr></thead><tbody id="routes"></tbody></table>
            </section>
          </main>
          <script>
            const data = {{data}};
            const escapeHtml = value => String(value ?? "").replace(/[&<>"']/g, character => ({
              "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;"
            })[character]);
            document.getElementById("repository").textContent = data.repository;
            const metrics = [
              ["API operations", data.apiOperations.length],
              ["Read-only operations", data.apiOperations.filter(item => item.readOnly).length],
              ["UI routes", data.uiRoutes.length],
              ["Query candidates", data.queryCandidates.length]
            ];
            document.getElementById("metrics").innerHTML = metrics
              .map(([label, value]) => `<div class="card"><span>${escapeHtml(label)}</span><strong>${value}</strong></div>`)
              .join("");
            document.getElementById("queries").innerHTML = data.queryCandidates
              .map(item => `<tr><td>${escapeHtml(item.prompt)}</td><td><code>${escapeHtml(item.operationId)}</code></td><td>${escapeHtml(item.viewPath || "Review required")}</td><td>${escapeHtml(item.parameters.join(", ") || "None")}</td></tr>`)
              .join("");
            document.getElementById("operations").innerHTML = data.apiOperations
              .map(item => `<tr><td>${escapeHtml(item.method)}</td><td><code>${escapeHtml(item.route)}</code></td><td class="${item.readOnly ? "safe" : "blocked"}">${item.readOnly ? "Read-only candidate" : "Excluded mutation"}</td><td>${escapeHtml(item.source)}</td></tr>`)
              .join("");
            document.getElementById("routes").innerHTML = data.uiRoutes
              .map(item => `<tr><td><code>${escapeHtml(item.path)}</code></td><td>${escapeHtml(item.source)}</td></tr>`)
              .join("");
          </script>
        </body>
        </html>
        """;
    }

    private static string Escape(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string NullableString(string? value) =>
        value is null ? "null" : $"\"{Escape(value)}\"";
}
