using System.Text.Json;
using System.Text.RegularExpressions;

namespace PortalCraft.RepoTool;

public sealed class IntegrationGenerator
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
    };

    public GenerationResult Generate(
        RepositoryProfile profile,
        string outputDirectory,
        bool force = false)
    {
        var output = Path.GetFullPath(outputDirectory);
        if (Directory.Exists(output)
            && Directory.EnumerateFileSystemEntries(output).Any()
            && !force)
        {
            throw new InvalidOperationException(
                $"Output directory is not empty: {output}. Pass --force to replace generated files.");
        }

        Directory.CreateDirectory(output);
        var files = new List<string>();
        Write(
            output,
            "portalcraft-ai.manifest.json",
            JsonSerializer.Serialize(profile, JsonOptions),
            files);
        Write(output, "server/PortalCraftGeneratedCatalog.cs", BuildServerCatalog(profile), files);
        Write(output, "client/portalCraft.generated.ts", BuildClientCatalog(profile), files);
        Write(output, "client/portalCraftAssistant.generated.ts", BuildAssistantIntegration(profile, []), files);
        Write(output, "client/PortalCraftGeneratedPanel.tsx", BuildClientPanel(), files);
        Write(output, "dashboard/index.html", BuildDashboard(profile), files);
        Write(output, "README.md", BuildReadme(profile), files);
        return new(profile, output, files);
    }

    public string GenerateAssistantIntegration(
        RepositoryProfile profile,
        string outputFile,
        IReadOnlyList<RepositoryDocument>? helpDocuments = null,
        bool force = false,
        PortalCraftAssistantConfiguration? assistantConfiguration = null)
    {
        var output = Path.GetFullPath(outputFile);
        if (File.Exists(output) && !force)
        {
            throw new InvalidOperationException(
                $"Output file already exists: {output}. Pass --force to replace the generated file.");
        }

        Directory.CreateDirectory(Path.GetDirectoryName(output)!);
        File.WriteAllText(
            output,
            BuildAssistantIntegration(
                profile,
                helpDocuments ?? [],
                ValidateAssistantConfiguration(assistantConfiguration)));
        return output;
    }

    private static void Write(
        string output,
        string relativePath,
        string content,
        ICollection<string> files)
    {
        var path = Path.Combine(output, relativePath.Replace('/', Path.DirectorySeparatorChar));
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, content);
        files.Add(path);
    }

    private static string BuildServerCatalog(RepositoryProfile profile)
    {
        var queries = string.Join(
            $",{Environment.NewLine}",
            profile.QueryCandidates.Select(candidate =>
                $"        new(\"{Escape(candidate.Id)}\", \"{Escape(candidate.Prompt)}\", " +
                $"\"{Escape(candidate.OperationId)}\", {NullableString(candidate.ViewPath)})"));

        return $$"""
            // Generated by PortalCraft.RepoTool. Review before integrating.
            using Microsoft.AspNetCore.Builder;
            using Microsoft.AspNetCore.Http;
            using Microsoft.AspNetCore.Routing;

            namespace PortalCraft.Generated;

            public sealed record PortalCraftGeneratedQuery(
                string Id,
                string Prompt,
                string OperationId,
                string? ViewPath);

            public static class PortalCraftGeneratedCatalog
            {
                public static readonly IReadOnlyList<PortalCraftGeneratedQuery> Queries =
                [
            {{queries}}
                ];

                public static IEndpointRouteBuilder MapPortalCraftGeneratedCatalog(
                    this IEndpointRouteBuilder endpoints)
                {
                    endpoints.MapGet("/api/portalcraft-ai/catalog", () => Results.Ok(Queries));
                    return endpoints;
                }
            }
            """;
    }

    private static string BuildClientCatalog(RepositoryProfile profile) =>
        $$"""
        // Generated by PortalCraft.RepoTool. Review before integrating.
        export type PortalCraftGeneratedQuery = {
          id: string;
          prompt: string;
          operationId: string;
          viewPath?: string;
        };

        export const portalCraftGeneratedQueries = {{JsonSerializer.Serialize(profile.QueryCandidates, JsonOptions)}} as const;
        """;

    private static string BuildAssistantIntegration(
        RepositoryProfile profile,
        IReadOnlyList<RepositoryDocument> helpDocuments,
        PortalCraftAssistantConfiguration? assistantConfiguration = null)
    {
        assistantConfiguration ??= new PortalCraftAssistantConfiguration();
        var views = profile.UiRoutes.Select(route => new
        {
            path = route.Path,
            tags = GetRouteTags(route.Path)
        });
        var helpTopics = BuildHelpTopics(helpDocuments);
        var helpSampleQuestions = helpDocuments
            .SelectMany(document => document.Sections.Count > 0
                ? document.Sections
                : [new RepositoryDocumentSection("Overview", document.Summary)])
            .Select(section => BuildHelpSampleQuestion(section.Title))
            .ToArray();
        var sampleQuestions = profile.QueryCandidates
            .Take(3)
            .Select(candidate => candidate.Prompt)
            .Concat(helpSampleQuestions)
            .ToArray();
        return $$"""
        // Generated by PortalCraft.RepoTool. Review before integrating.
        export type PortalCraftAssistantQuery = {
          id: string;
          prompt: string;
          operationId: string;
          viewPath?: string | null;
          parameters: readonly string[];
        };

        export type PortalCraftParsedQueryCommand = {
          query: PortalCraftAssistantQuery;
          parameters: Readonly<Record<string, unknown>>;
        };

        export type PortalCraftQueryResult = {
          title: string;
          summary?: string;
          fields?: readonly {
            label: string;
            value: string | number | boolean | null | undefined;
          }[];
          sections?: readonly {
            title: string;
            content: string;
          }[];
          actions?: readonly {
            label: string;
            url: string;
          }[];
        };

        export type PortalCraftQueryExecutor = (
          parameters: Readonly<Record<string, unknown>>,
          query: PortalCraftAssistantQuery
        ) => string | Promise<string>;

        export type PortalCraftQueryExecutors =
          Readonly<Record<string, PortalCraftQueryExecutor>>;

        export type PortalCraftAssistantView = {
          path: string;
          tags: readonly string[];
        };

        export type PortalCraftHelpTopic = {
          id: string;
          title: string;
          documentTitle: string;
          summary: string;
          sourceTitle: string;
          sourceUrl?: string | null;
          repositoryPath: string;
        };

        export type PortalCraftAssistantLookupKey = {
          id: string;
          label: string;
          example: string;
          aliases: readonly string[];
        };

        export type PortalCraftAssistantBusinessEntity = {
          id: string;
          label: string;
          group: string;
          aliases: readonly string[];
          requestRoute: string;
          requestActionLabel?: string | null;
          routeParameters: Readonly<Record<string, string>>;
        };

        export type PortalCraftAssistantRequirements = {
          assistantName: string;
          assistantIcon: "portalcraft" | "host-default";
          lookupKeys: readonly PortalCraftAssistantLookupKey[];
          businessEntities: readonly PortalCraftAssistantBusinessEntity[];
        };

        export const portalCraftAssistantRequirements: PortalCraftAssistantRequirements =
          {{JsonSerializer.Serialize(assistantConfiguration, JsonOptions)}};

        export const portalCraftAssistantIconDataUrl =
          portalCraftAssistantRequirements.assistantIcon === "portalcraft"
            ? "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Cpath fill='%23fff' d='M12 14h24c10 0 18 8 18 18s-8 18-18 18H24v-9h12a9 9 0 0 0 0-18H21v31h-9V14Z'/%3E%3Cpath fill='%2300a4ef' d='M28 27h8a5 5 0 1 1 0 10h-8V27Z'/%3E%3C/svg%3E"
            : undefined;

        export const portalCraftAssistantQueries =
          {{JsonSerializer.Serialize(profile.QueryCandidates, JsonOptions)}} as const;

        export const portalCraftQueryCommandPattern =
          /^run\s+portal\s+query\s+([a-z0-9-]+)(?:\s+with\s+(.+))?$/i;

        export const portalCraftQueryCommandDescription = [
          "`run portal query <query-id> with <json>` — execute one discovered read-only portal query",
          ...portalCraftAssistantQueries.map(query => {
            const parameters = query.parameters.length > 0
              ? `; parameters: ${query.parameters.join(", ")}`
              : "";
            return `${query.id}: ${query.prompt}${parameters}`;
          }),
        ].join("\n");

        export function describePortalCraftQueries(
          supportedOperationIds?: readonly string[]
        ): string {
          if (!supportedOperationIds) return portalCraftQueryCommandDescription;
          const supported = new Set(supportedOperationIds);
          return [
            "`run portal query <query-id> with <json>` — execute one discovered read-only portal query",
            ...portalCraftAssistantQueries
              .filter(query => supported.has(query.operationId))
              .map(query => {
                const parameters = query.parameters.length > 0
                  ? `; parameters: ${query.parameters.join(", ")}`
                  : "";
                return `${query.id}: ${query.prompt}${parameters}`;
              }),
          ].join("\n");
        }

        export const portalCraftAssistantViews =
          {{JsonSerializer.Serialize(views, JsonOptions)}} as const;

        export const portalCraftHelpTopics =
          {{JsonSerializer.Serialize(helpTopics, JsonOptions)}} as const;

        export const portalCraftHelpSampleQuestions =
          {{JsonSerializer.Serialize(helpSampleQuestions, JsonOptions)}} as const;

        export const portalCraftAssistantSampleQuestions =
          {{JsonSerializer.Serialize(sampleQuestions, JsonOptions)}} as const;

        export const portalCraftAssistantSetup = {
          assistantName: portalCraftAssistantRequirements.assistantName,
          supportedQuestionTypes: [
            "Read-only portal data and request lookups",
            "Reviewed help-document process and definition questions",
            "Greetings, capabilities, and thanks",
          ],
          sampleQuestions: portalCraftAssistantSampleQuestions,
          parsedHelpTopicCount: portalCraftHelpTopics.length,
          reviewedDocuments: Array.from(new Set(
            portalCraftHelpTopics.map(topic => topic.documentTitle)
          )),
          lookupKeys: portalCraftAssistantRequirements.lookupKeys,
          businessEntities: portalCraftAssistantRequirements.businessEntities,
        } as const;

        const SAFE_PARAMETER_NAME = /^[A-Za-z][A-Za-z0-9]{0,63}$/;
        const SAFE_HELP_TOPIC_ID = /^[a-z0-9][a-z0-9-]{0,159}$/;
        const QUERY_STOP_WORDS = new Set([
          "about", "data", "find", "for", "from", "get", "give", "lookup",
          "me", "please", "request", "requests", "search", "show", "the",
          "with"
        ]);
        const HELP_STOP_WORDS = new Set([
          "about", "after", "also", "before", "could", "does", "from", "have",
          "help", "into", "need", "please", "should", "that", "the", "their",
          "then", "there", "this", "what", "when", "where", "which", "with",
          "would", "your"
        ]);
        const MIN_HELP_TOPIC_SCORE = 3;

        export const portalCraftHelpCommandDescription = [
          "`explain help topic <topic-id>` — answer only from a reviewed help-document topic",
          ...portalCraftHelpTopics.map(topic =>
            `${topic.id}: ${topic.documentTitle} — ${topic.title}: ${topic.summary.slice(0, 220)}`
          ),
        ].join("\n");

        function queryTerms(value: string): string[] {
          return (value.toLowerCase().match(/[a-z0-9]+/g) || [])
            .filter(term => term.length > 1 && !QUERY_STOP_WORDS.has(term));
        }

        function queryScore(
          terms: readonly string[],
          query: PortalCraftAssistantQuery
        ): number {
          const prompt = query.prompt.toLowerCase();
          const identity = `${query.id} ${query.operationId}`.toLowerCase();
          return terms.reduce((score, term) => {
            if (prompt.includes(term)) return score + 3;
            if (identity.includes(term)) return score + 1;
            return score;
          }, 0);
        }

        export function findPortalCraftAssistantQuery(
          question: string
        ): PortalCraftAssistantQuery | undefined {
          const terms = queryTerms(question);
          if (terms.length === 0) return undefined;
          const best = portalCraftAssistantQueries
            .map(query => ({ query, score: queryScore(terms, query) }))
            .filter(item => item.score > 0)
            .sort((left, right) => right.score - left.score)[0];
          return best && best.score >= Math.min(4, terms.length * 2)
            ? best.query
            : undefined;
        }

        function parseQueryParameters(
          query: PortalCraftAssistantQuery,
          json: string | undefined
        ): Readonly<Record<string, unknown>> {
          if (!json) {
            if (query.parameters.length > 0) {
              throw new Error(`Missing query parameters: ${query.parameters.join(", ")}.`);
            }
            return {};
          }
          if (json.length > 4000) {
            throw new Error("Query parameters exceed the 4000-character limit.");
          }
          let parsed: unknown;
          try {
            parsed = JSON.parse(json);
          } catch {
            throw new Error("Query parameters must be a valid JSON object.");
          }
          if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
            throw new Error("Query parameters must be a JSON object.");
          }
          const parameters = parsed as Record<string, unknown>;
          const names = Object.keys(parameters);
          if (!names.every(name => SAFE_PARAMETER_NAME.test(name))) {
            throw new Error("Query parameters contain an invalid name.");
          }
          const allowed = new Set(query.parameters);
          const unsupported = names.filter(name => !allowed.has(name));
          if (unsupported.length > 0) {
            throw new Error(`Unsupported query parameters: ${unsupported.join(", ")}.`);
          }
          const missing = query.parameters.filter(
            name => !Object.prototype.hasOwnProperty.call(parameters, name)
          );
          if (missing.length > 0) {
            throw new Error(`Missing query parameters: ${missing.join(", ")}.`);
          }
          return parameters;
        }

        export function parsePortalCraftQueryCommand(
          input: string
        ): PortalCraftParsedQueryCommand | undefined {
          const match = input.trim().match(portalCraftQueryCommandPattern);
          if (!match) return undefined;
          const query = portalCraftAssistantQueries.find(candidate => candidate.id === match[1]);
          if (!query) {
            throw new Error(`Unknown read-only portal query "${match[1]}".`);
          }
          return {
            query,
            parameters: parseQueryParameters(query, match[2]),
          };
        }

        export function buildPortalCraftQueryCommand(
          queryId: string,
          parameters: Readonly<Record<string, unknown>> = {}
        ): string {
          const json = Object.keys(parameters).length > 0
            ? ` with ${JSON.stringify(parameters)}`
            : "";
          const command = `run portal query ${queryId}${json}`;
          parsePortalCraftQueryCommand(command);
          return command;
        }

        export async function executePortalCraftQueryCommand(
          input: string,
          executors: PortalCraftQueryExecutors
        ): Promise<string | undefined> {
          const parsed = parsePortalCraftQueryCommand(input);
          if (!parsed) return undefined;
          const executor = executors[parsed.query.operationId];
          if (!executor) {
            throw new Error(
              `No authorized executor is registered for "${parsed.query.operationId}".`
            );
          }
          return executor(parsed.parameters, parsed.query);
        }

        function isSafeResultActionUrl(url: string): boolean {
          return (url.startsWith("/") && !url.startsWith("//")) ||
            url.startsWith("https://");
        }

        export function formatPortalCraftQueryResult(
          result: PortalCraftQueryResult
        ): string {
          const title = result.title.trim();
          if (!title) throw new Error("A query result title is required.");
          const lines = [`**${title}**`];
          if (result.summary?.trim()) lines.push(result.summary.trim());
          const fields = (result.fields || []).filter(
            field => field.value !== null &&
              field.value !== undefined &&
              String(field.value).trim().length > 0
          );
          if (fields.length > 0) {
            lines.push("");
            fields.forEach(field => {
              lines.push(`**${field.label}:** ${String(field.value)}`);
            });
          }
          (result.sections || []).forEach(section => {
            if (!section.title.trim() || !section.content.trim()) return;
            lines.push("", `**${section.title.trim()}**`, section.content.trim());
          });
          const actions = (result.actions || []).filter(action => {
            if (!action.label.trim() || !isSafeResultActionUrl(action.url)) {
              throw new Error("Query result actions require a label and a safe portal or HTTPS URL.");
            }
            return true;
          });
          if (actions.length > 0) {
            lines.push("", actions.map(
              action => `[${action.label.trim()}](${action.url})`
            ).join(" · "));
          }
          return lines.join("\n");
        }

        function escapePortalCraftRegex(value: string): string {
          return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
        }

        export const portalCraftLookupClarificationPatterns: readonly RegExp[] = (() => {
          const aliases = portalCraftAssistantRequirements.lookupKeys
            .flatMap(key => key.aliases)
            .filter(Boolean)
            .sort((left, right) => right.length - left.length)
            .map(escapePortalCraftRegex);
          if (aliases.length === 0 ||
              portalCraftAssistantRequirements.businessEntities.length === 0) {
            return [];
          }
          const lookup = `(?:${aliases.join("|")})`;
          return [new RegExp(
            `^(?:can\\s+you\\s+|i\\s+want\\s+to\\s+)?` +
            `(?:find|search|show|fetch|look\\s*up)(?:\\s+me)?(?:\\s+(?:a|the|by))?` +
            `\\s+${lookup}(?:\\s+or\\s+${lookup})*[?.]*$`,
            "i"
          )];
        })();

        export function answerPortalCraftLookupClarification(
          input: string
        ): string | undefined {
          const { lookupKeys, businessEntities } = portalCraftAssistantRequirements;
          if (!portalCraftLookupClarificationPatterns.some(
            pattern => pattern.test(input.trim())
          )) return undefined;

          const lines = [
            `**Find a request in ${portalCraftAssistantRequirements.assistantName}**`,
            "Which identifier do you have?",
            ...lookupKeys.map(key =>
              `- **${key.label}**${key.example ? ` — for example \`${key.example}\`` : ""}`
            ),
            "",
            "Which business entity should I search?",
          ];
          const groups = Array.from(new Set(businessEntities.map(entity => entity.group)));
          groups.forEach(group => {
            const labels = businessEntities
              .filter(entity => entity.group === group)
              .map(entity => entity.label);
            lines.push(`- **${group}:** ${labels.join(", ")}`);
          });
          lines.push(
            "",
            "After you provide the identifier and entity, I’ll return the matching request with a link that opens it highlighted in the portal."
          );
          return lines.join("\n");
        }

        export function buildPortalCraftRequestAction(
          entityId: string,
          requestId: string
        ): { label: string; url: string } {
          const entity = portalCraftAssistantRequirements.businessEntities.find(
            candidate => candidate.id.toLowerCase() === entityId.toLowerCase()
          );
          if (!entity) throw new Error(`Unknown portal business entity "${entityId}".`);
          const normalizedRequestId = requestId.trim();
          if (!normalizedRequestId) throw new Error("A request ID is required.");
          const parameters: Record<string, string> = {
            requestId: normalizedRequestId,
            highlightRequest: normalizedRequestId,
            ...entity.routeParameters,
          };
          const query = Object.entries(parameters)
            .map(([key, value]) =>
              `${encodeURIComponent(key)}=${encodeURIComponent(value)}`
            )
            .join("&");
          return {
            label: `Open highlighted ${entity.requestActionLabel || entity.label} request`,
            url: `${entity.requestRoute}?${query}`,
          };
        }

        export const portalCraftConversationPatterns = [
          /^(?:hi|hello|hey)(?:\s+(?:there|assistant))?[!.?]*$/i,
          /^good\s+(?:morning|afternoon|evening)(?:\s+(?:there|assistant))?[!.?]*$/i,
          /^(?:what\s+can\s+(?:you|i)\s+(?:do|ask)|how\s+can\s+you\s+help(?:\s+me)?|who\s+are\s+you|tell\s+me\s+about\s+yourself)[!.?]*$/i,
          /^(?:thanks|thank\s+you|thanks\s+for\s+your\s+help)[!.?]*$/i,
        ] as const;

        export const portalCraftHelpQuestionPatterns = [
          /^explain\s+help\s+topic\s+([a-z0-9-]+)\.?$/i,
          /^what\s+does\s+(.+?)\s+mean(?:\s+in\s+.+)?[?.]*$/i,
          /^(?:what\s+is|define|explain|meaning\s+of)\s+(.+?)[?.]*$/i,
          /^(.+?)\s+(?:meaning|definition)[?.]*$/i,
        ] as const;

        export const portalCraftAssistantScopeInstruction = [
          "Respond conversationally to greetings, thanks, and questions about assistant capabilities.",
          "For portal questions, use only generated read-only query commands or reviewed help-document topics.",
          "Do not answer from model knowledge.",
          "If a question is outside the portal or reviewed documents, explain the supported scope briefly, suggest one available example, and return no commands.",
        ].join(" ");

        function portalCraftCapabilityExamples(): string[] {
          return portalCraftAssistantSampleQuestions.slice(0, 5)
            .map(question => `• ${question}`);
        }

        export function answerPortalCraftConversation(
          input: string,
          assistantName = "Portal Assistant"
        ): string | undefined {
          const normalized = input.trim();
          if (portalCraftConversationPatterns.slice(0, 3).some(pattern => pattern.test(normalized))) {
            const examples = portalCraftCapabilityExamples();
            return [
              `Hi! I'm ${assistantName}.`,
              "I can run verified read-only portal queries and answer from reviewed help documents.",
              ...(examples.length > 0 ? ["", "Try asking:", ...examples] : []),
            ].join("\n");
          }
          if (portalCraftConversationPatterns[3].test(normalized)) {
            return "You're welcome. Ask another portal or reviewed help-document question whenever you're ready.";
          }
          return undefined;
        }

        function isSafeParameterValue(value: string): boolean {
          return value.length > 0 &&
            value.length <= 200 &&
            !Array.from(value).some(character => {
              const code = character.charCodeAt(0);
              return code < 32 || code === 127;
            });
        }

        export function findPortalCraftAssistantView(
          requiredTags: readonly string[]
        ): string | undefined {
          const normalizedTags = requiredTags
            .map(tag => tag.trim().toLowerCase())
            .filter(Boolean);
          return portalCraftAssistantViews
            .filter(view => normalizedTags.every(
              tag => (view.tags as readonly string[]).includes(tag)
            ))
            .sort((left, right) => left.path.length - right.path.length)[0]?.path;
        }

        export function buildPortalCraftAssistantRoute(
          requiredTags: readonly string[],
          parameters: Readonly<Record<string, string>>
        ): string | undefined {
          const path = findPortalCraftAssistantView(requiredTags);
          if (!path || !path.startsWith("/") || path.startsWith("//")) return undefined;
          const entries: Array<[string, string]> = Object.entries(parameters)
            .map(([name, value]) => [name, value.trim()]);
          if (!entries.every(
            ([name, value]) => SAFE_PARAMETER_NAME.test(name) && isSafeParameterValue(value)
          )) return undefined;
          const suffix = new URLSearchParams(entries).toString();
          return suffix ? `${path}?${suffix}` : path;
        }

        function helpTerms(value: string): string[] {
          return (value.toLowerCase().match(/[a-z0-9]+/g) || [])
            .filter(term => term.length > 2 && !HELP_STOP_WORDS.has(term));
        }

        function helpTopicScore(
          terms: readonly string[],
          topic: PortalCraftHelpTopic
        ): number {
          if (topic.title.trim().toLowerCase() === topic.documentTitle.trim().toLowerCase()) {
            return 0;
          }
          const title = topic.title.toLowerCase();
          const summary = topic.summary.toLowerCase();
          return terms.reduce((score, term) => {
            if (title.includes(term)) return score + 3;
            if (summary.includes(term)) return score + 1;
            return score;
          }, 0);
        }

        export function findPortalCraftHelpTopic(
          topicIdOrQuestion: string
        ): PortalCraftHelpTopic | undefined {
          const normalized = topicIdOrQuestion.trim().toLowerCase();
          if (SAFE_HELP_TOPIC_ID.test(normalized)) {
            const exact = portalCraftHelpTopics.find(topic => topic.id === normalized);
            if (exact) return exact;
          }
          const terms = helpTerms(topicIdOrQuestion);
          if (terms.length === 0) return undefined;
          return portalCraftHelpTopics
            .map(topic => ({ topic, score: helpTopicScore(terms, topic) }))
            .filter(item => item.score >= MIN_HELP_TOPIC_SCORE)
            .sort((left, right) => right.score - left.score)[0]?.topic;
        }

        export function answerPortalCraftHelpTopic(
          topicIdOrQuestion: string
        ): string {
          const topic = findPortalCraftHelpTopic(topicIdOrQuestion);
          if (!topic) {
            return "No verified help-document topic matched that question.";
          }
          const citation = topic.sourceUrl
            ? `[${topic.sourceTitle}](${topic.sourceUrl})`
            : `${topic.sourceTitle} (${topic.repositoryPath})`;
          return [
            `**${topic.documentTitle} — ${topic.title}**`,
            topic.summary,
            "",
            `Source: ${citation}`,
          ].join("\n");
        }

        export function answerPortalCraftHelpQuestion(
          input: string
        ): string | undefined {
          const match = portalCraftHelpQuestionPatterns
            .map(pattern => input.trim().match(pattern))
            .find(candidate => candidate !== null);
          if (!match) return undefined;
          const topic = findPortalCraftHelpTopic(match[1] || match[0]);
          return topic ? answerPortalCraftHelpTopic(topic.id) : undefined;
        }
        """;
    }

    private static PortalCraftAssistantConfiguration? ValidateAssistantConfiguration(
        PortalCraftAssistantConfiguration? configuration)
    {
        if (configuration is null)
        {
            return null;
        }
        if (string.IsNullOrWhiteSpace(configuration.AssistantName))
        {
            throw new InvalidOperationException("Assistant configuration requires assistantName.");
        }
        if (configuration.AssistantIcon is not ("portalcraft" or "host-default"))
        {
            throw new InvalidOperationException(
                "Assistant configuration assistantIcon must be portalcraft or host-default.");
        }
        if (configuration.LookupKeys.Select(key => key.Id).Distinct(StringComparer.OrdinalIgnoreCase).Count()
            != configuration.LookupKeys.Count)
        {
            throw new InvalidOperationException("Assistant lookup key IDs must be unique.");
        }
        foreach (var key in configuration.LookupKeys)
        {
            if (string.IsNullOrWhiteSpace(key.Id)
                || string.IsNullOrWhiteSpace(key.Label)
                || key.Aliases.Count == 0
                || key.Aliases.Any(string.IsNullOrWhiteSpace))
            {
                throw new InvalidOperationException(
                    "Each assistant lookup key requires an id, label, and at least one alias.");
            }
        }
        if (configuration.BusinessEntities
            .Select(entity => entity.Id)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .Count() != configuration.BusinessEntities.Count)
        {
            throw new InvalidOperationException("Assistant business entity IDs must be unique.");
        }
        foreach (var entity in configuration.BusinessEntities)
        {
            if (string.IsNullOrWhiteSpace(entity.Id)
                || string.IsNullOrWhiteSpace(entity.Label)
                || string.IsNullOrWhiteSpace(entity.Group)
                || entity.Aliases.Count == 0
                || entity.Aliases.Any(string.IsNullOrWhiteSpace)
                || !entity.RequestRoute.StartsWith("/", StringComparison.Ordinal)
                || entity.RequestRoute.StartsWith("//", StringComparison.Ordinal))
            {
                throw new InvalidOperationException(
                    "Each assistant business entity requires an id, label, group, aliases, and a safe portal requestRoute.");
            }
        }
        return configuration;
    }

    private static string BuildHelpSampleQuestion(string title)
    {
        var subject = Regex.Replace(title, @"^\d+(?:\.\d+)*\s*", "").Trim();
        return $"Explain {(subject.Length > 0 ? subject : "this help topic")}";
    }

    private static IReadOnlyList<object> BuildHelpTopics(
        IReadOnlyList<RepositoryDocument> documents)
    {
        var topics = new List<object>();
        var usedIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var document in documents)
        {
            var sections = document.Sections.Count > 0
                ? document.Sections
                : [new RepositoryDocumentSection("Overview", document.Summary)];
            foreach (var section in sections)
            {
                var baseId = ToSlug($"{document.Title}-{section.Title}");
                var id = baseId;
                var suffix = 2;
                while (!usedIds.Add(id))
                {
                    id = $"{baseId}-{suffix}";
                    suffix += 1;
                }
                topics.Add(new
                {
                    id,
                    section.Title,
                    documentTitle = document.Title,
                    section.Summary,
                    sourceTitle = document.SourceTitle ?? document.Title,
                    document.SourceUrl,
                    repositoryPath = document.Path
                });
            }
        }
        return topics;
    }

    private static string BuildClientPanel() =>
        """
        import { portalCraftGeneratedQueries } from "./portalCraft.generated";

        type Props = {
          assistantName?: string;
          onAsk: (prompt: string) => void;
        };

        export function PortalCraftGeneratedPanel({
          assistantName = "PortalCraft AI",
          onAsk,
        }: Props) {
          return (
            <aside aria-label={assistantName}>
              <h2>{assistantName}</h2>
              <p>Repository-discovered, read-only query starters</p>
              <div>
                {portalCraftGeneratedQueries.map(query => (
                  <button key={query.id} type="button" onClick={() => onAsk(query.prompt)}>
                    {query.prompt}
                  </button>
                ))}
              </div>
            </aside>
          );
        }
        """;

    private static string BuildReadme(RepositoryProfile profile) =>
        $$"""
        # Generated PortalCraft AI onboarding

        The repository tool discovered:

        - {{profile.ApiOperations.Count}} API operations
        - {{profile.ApiOperations.Count(operation => operation.ReadOnly)}} read-only API operations
        - {{profile.UiRoutes.Count}} UI routes
        - {{profile.QueryCandidates.Count}} query candidates

        ## Integration

        1. Review `portalcraft-ai.manifest.json`; remove false positives and add product-owned authorization requirements.
        2. Copy `server/PortalCraftGeneratedCatalog.cs` into the ASP.NET Core project and call
           `app.MapPortalCraftGeneratedCatalog()`.
        3. Copy the generated client files into the React application.
        4. Use `portalCraftAssistant.generated.ts` to resolve reviewed in-portal search and
           validator destinations instead of hard-coding product routes.
        5. Connect `onAsk` to the product's governed PortalCraft AI chat endpoint.
        6. Implement typed handlers for approved operations. The generator never exposes write operations automatically.

        Generated files are scaffolding, not an authorization boundary. Product APIs must continue to enforce
        authentication, authorization, validation, audit, and data classification.

        ## Preview

        From the PortalCraft AI source repository:

        `dotnet run --project tools/PortalCraft.RepoTool -- serve "{{profile.Repository}}/.portalcraft-ai"`
        """;

    private static string BuildDashboard(RepositoryProfile profile)
    {
        var data = JsonSerializer.Serialize(profile, JsonOptions)
            .Replace("</", "<\\/", StringComparison.Ordinal);
        return $$"""
        <!doctype html>
        <html lang="en">
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <title>PortalCraft AI repository dashboard</title>
          <style>
            :root { font-family: Segoe UI, Arial, sans-serif; color: #172033; background: #eef3f8; }
            body { margin: 0; }
            header { padding: 22px 30px; color: white; background: #172033; }
            header h1 { margin: 0 0 5px; }
            header p { margin: 0; color: #c9d6e5; }
            main { padding: 26px 30px 50px; }
            .metrics { display: grid; grid-template-columns: repeat(4, minmax(150px, 1fr)); gap: 14px; }
            .card, section { border: 1px solid #d7dee8; border-radius: 12px; background: white; box-shadow: 0 3px 12px #1720330d; }
            .card { padding: 18px; }
            .card span { display: block; color: #5b6879; font-size: 13px; }
            .card strong { display: block; margin-top: 8px; font-size: 30px; }
            section { margin-top: 20px; padding: 20px; overflow-x: auto; }
            h2 { margin: 0 0 15px; }
            table { width: 100%; border-collapse: collapse; font-size: 13px; }
            th, td { padding: 10px; border-bottom: 1px solid #edf1f5; text-align: left; vertical-align: top; }
            th { color: #526173; }
            code { color: #005a9e; }
            .safe { color: #107c10; font-weight: 700; }
            .blocked { color: #a4262c; font-weight: 700; }
            @media (max-width: 800px) { .metrics { grid-template-columns: repeat(2, 1fr); } main { padding: 18px; } }
          </style>
        </head>
        <body>
          <header>
            <h1>PortalCraft AI repository dashboard</h1>
            <p id="repository"></p>
          </header>
          <main>
            <div class="metrics" id="metrics"></div>
            <section>
              <h2>Suggested read-only queries</h2>
              <table><thead><tr><th>Prompt</th><th>Operation</th><th>View</th><th>Parameters</th></tr></thead><tbody id="queries"></tbody></table>
            </section>
            <section>
              <h2>Discovered API operations</h2>
              <table><thead><tr><th>Method</th><th>Route</th><th>Classification</th><th>Source</th></tr></thead><tbody id="operations"></tbody></table>
            </section>
            <section>
              <h2>Discovered UI routes</h2>
              <table><thead><tr><th>Route</th><th>Source</th></tr></thead><tbody id="routes"></tbody></table>
            </section>
          </main>
          <script>
            const data = {{data}};
            const escapeHtml = value => String(value ?? "").replace(/[&<>"']/g, character => ({
              "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;"
            })[character]);
            document.getElementById("repository").textContent = data.repository;
            const metrics = [
              ["API operations", data.apiOperations.length],
              ["Read-only operations", data.apiOperations.filter(item => item.readOnly).length],
              ["UI routes", data.uiRoutes.length],
              ["Query candidates", data.queryCandidates.length]
            ];
            document.getElementById("metrics").innerHTML = metrics
              .map(([label, value]) => `<div class="card"><span>${escapeHtml(label)}</span><strong>${value}</strong></div>`)
              .join("");
            document.getElementById("queries").innerHTML = data.queryCandidates
              .map(item => `<tr><td>${escapeHtml(item.prompt)}</td><td><code>${escapeHtml(item.operationId)}</code></td><td>${escapeHtml(item.viewPath || "Review required")}</td><td>${escapeHtml(item.parameters.join(", ") || "None")}</td></tr>`)
              .join("");
            document.getElementById("operations").innerHTML = data.apiOperations
              .map(item => `<tr><td>${escapeHtml(item.method)}</td><td><code>${escapeHtml(item.route)}</code></td><td class="${item.readOnly ? "safe" : "blocked"}">${item.readOnly ? "Read-only candidate" : "Excluded mutation"}</td><td>${escapeHtml(item.source)}</td></tr>`)
              .join("");
            document.getElementById("routes").innerHTML = data.uiRoutes
              .map(item => `<tr><td><code>${escapeHtml(item.path)}</code></td><td>${escapeHtml(item.source)}</td></tr>`)
              .join("");
          </script>
        </body>
        </html>
        """;
    }

    private static string Escape(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string NullableString(string? value) =>
        value is null ? "null" : $"\"{Escape(value)}\"";

    private static IReadOnlyList<string> GetRouteTags(string route) =>
        Words(route)
            .Select(word => word.ToLowerInvariant())
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToArray();

    private static string ToSlug(string value)
    {
        var words = Words(value)
            .SelectMany(word => System.Text.RegularExpressions.Regex
                .Matches(word.ToLowerInvariant(), "[a-z0-9]+")
                .Cast<System.Text.RegularExpressions.Match>()
                .Select(match => match.Value))
            .Where(word => word.Length > 0)
            .Take(18)
            .ToArray();
        var slug = string.Join("-", words);
        if (slug.Length == 0)
        {
            return "help-topic";
        }
        return slug.Length <= 150 ? slug : slug[..150].TrimEnd('-');
    }

    private static IEnumerable<string> Words(string value) =>
        System.Text.RegularExpressions.Regex
            .Replace(value, "([a-z0-9])([A-Z])", "$1 $2")
            .Split(['/', '-', '_', ' '], StringSplitOptions.RemoveEmptyEntries);
}
