using System.Text.Json;

namespace PortalCraft.RepoTool;

public sealed class IntegrationGenerator
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
    };

    public GenerationResult Generate(
        RepositoryProfile profile,
        string outputDirectory,
        bool force = false)
    {
        var output = Path.GetFullPath(outputDirectory);
        if (Directory.Exists(output)
            && Directory.EnumerateFileSystemEntries(output).Any()
            && !force)
        {
            throw new InvalidOperationException(
                $"Output directory is not empty: {output}. Pass --force to replace generated files.");
        }

        Directory.CreateDirectory(output);
        var files = new List<string>();
        Write(
            output,
            "portalcraft-ai.manifest.json",
            JsonSerializer.Serialize(profile, JsonOptions),
            files);
        Write(output, "server/PortalCraftGeneratedCatalog.cs", BuildServerCatalog(profile), files);
        Write(output, "client/portalCraft.generated.ts", BuildClientCatalog(profile), files);
        Write(output, "client/portalCraftAssistant.generated.ts", BuildAssistantIntegration(profile, []), files);
        Write(output, "client/PortalCraftGeneratedPanel.tsx", BuildClientPanel(), files);
        Write(output, "dashboard/index.html", BuildDashboard(profile), files);
        Write(output, "README.md", BuildReadme(profile), files);
        return new(profile, output, files);
    }

    public string GenerateAssistantIntegration(
        RepositoryProfile profile,
        string outputFile,
        IReadOnlyList<RepositoryDocument>? helpDocuments = null,
        bool force = false)
    {
        var output = Path.GetFullPath(outputFile);
        if (File.Exists(output) && !force)
        {
            throw new InvalidOperationException(
                $"Output file already exists: {output}. Pass --force to replace the generated file.");
        }

        Directory.CreateDirectory(Path.GetDirectoryName(output)!);
        File.WriteAllText(output, BuildAssistantIntegration(profile, helpDocuments ?? []));
        return output;
    }

    private static void Write(
        string output,
        string relativePath,
        string content,
        ICollection<string> files)
    {
        var path = Path.Combine(output, relativePath.Replace('/', Path.DirectorySeparatorChar));
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, content);
        files.Add(path);
    }

    private static string BuildServerCatalog(RepositoryProfile profile)
    {
        var queries = string.Join(
            $",{Environment.NewLine}",
            profile.QueryCandidates.Select(candidate =>
                $"        new(\"{Escape(candidate.Id)}\", \"{Escape(candidate.Prompt)}\", " +
                $"\"{Escape(candidate.OperationId)}\", {NullableString(candidate.ViewPath)})"));

        return $$"""
            // Generated by PortalCraft.RepoTool. Review before integrating.
            using Microsoft.AspNetCore.Builder;
            using Microsoft.AspNetCore.Http;
            using Microsoft.AspNetCore.Routing;

            namespace PortalCraft.Generated;

            public sealed record PortalCraftGeneratedQuery(
                string Id,
                string Prompt,
                string OperationId,
                string? ViewPath);

            public static class PortalCraftGeneratedCatalog
            {
                public static readonly IReadOnlyList<PortalCraftGeneratedQuery> Queries =
                [
            {{queries}}
                ];

                public static IEndpointRouteBuilder MapPortalCraftGeneratedCatalog(
                    this IEndpointRouteBuilder endpoints)
                {
                    endpoints.MapGet("/api/portalcraft-ai/catalog", () => Results.Ok(Queries));
                    return endpoints;
                }
            }
            """;
    }

    private static string BuildClientCatalog(RepositoryProfile profile) =>
        $$"""
        // Generated by PortalCraft.RepoTool. Review before integrating.
        export type PortalCraftGeneratedQuery = {
          id: string;
          prompt: string;
          operationId: string;
          viewPath?: string;
        };

        export const portalCraftGeneratedQueries = {{JsonSerializer.Serialize(profile.QueryCandidates, JsonOptions)}} as const;
        """;

    private static string BuildAssistantIntegration(
        RepositoryProfile profile,
        IReadOnlyList<RepositoryDocument> helpDocuments)
    {
        var views = profile.UiRoutes.Select(route => new
        {
            path = route.Path,
            tags = GetRouteTags(route.Path)
        });
        var helpTopics = BuildHelpTopics(helpDocuments);
        return $$"""
        // Generated by PortalCraft.RepoTool. Review before integrating.
        export type PortalCraftAssistantQuery = {
          id: string;
          prompt: string;
          operationId: string;
          viewPath?: string;
          parameters: readonly string[];
        };

        export type PortalCraftAssistantView = {
          path: string;
          tags: readonly string[];
        };

        export type PortalCraftHelpTopic = {
          id: string;
          title: string;
          documentTitle: string;
          summary: string;
          sourceTitle: string;
          sourceUrl?: string | null;
          repositoryPath: string;
        };

        export const portalCraftAssistantQueries =
          {{JsonSerializer.Serialize(profile.QueryCandidates, JsonOptions)}} as const;

        export const portalCraftAssistantViews =
          {{JsonSerializer.Serialize(views, JsonOptions)}} as const;

        export const portalCraftHelpTopics =
          {{JsonSerializer.Serialize(helpTopics, JsonOptions)}} as const;

        const SAFE_PARAMETER_NAME = /^[A-Za-z][A-Za-z0-9]{0,63}$/;
        const SAFE_HELP_TOPIC_ID = /^[a-z0-9][a-z0-9-]{0,159}$/;
        const HELP_STOP_WORDS = new Set([
          "about", "after", "also", "before", "could", "does", "from", "have",
          "help", "into", "need", "please", "should", "that", "the", "their",
          "then", "there", "this", "what", "when", "where", "which", "with",
          "would", "your"
        ]);

        export const portalCraftHelpCommandDescription = [
          "`explain help topic <topic-id>` — answer only from a reviewed help-document topic",
          ...portalCraftHelpTopics.map(topic =>
            `${topic.id}: ${topic.documentTitle} — ${topic.title}: ${topic.summary.slice(0, 220)}`
          ),
        ].join("\n");

        function isSafeParameterValue(value: string): boolean {
          return value.length > 0 &&
            value.length <= 200 &&
            !Array.from(value).some(character => {
              const code = character.charCodeAt(0);
              return code < 32 || code === 127;
            });
        }

        export function findPortalCraftAssistantView(
          requiredTags: readonly string[]
        ): string | undefined {
          const normalizedTags = requiredTags
            .map(tag => tag.trim().toLowerCase())
            .filter(Boolean);
          return portalCraftAssistantViews
            .filter(view => normalizedTags.every(
              tag => (view.tags as readonly string[]).includes(tag)
            ))
            .sort((left, right) => left.path.length - right.path.length)[0]?.path;
        }

        export function buildPortalCraftAssistantRoute(
          requiredTags: readonly string[],
          parameters: Readonly<Record<string, string>>
        ): string | undefined {
          const path = findPortalCraftAssistantView(requiredTags);
          if (!path || !path.startsWith("/") || path.startsWith("//")) return undefined;
          const entries: Array<[string, string]> = Object.entries(parameters)
            .map(([name, value]) => [name, value.trim()]);
          if (!entries.every(
            ([name, value]) => SAFE_PARAMETER_NAME.test(name) && isSafeParameterValue(value)
          )) return undefined;
          const suffix = new URLSearchParams(entries).toString();
          return suffix ? `${path}?${suffix}` : path;
        }

        function helpTerms(value: string): string[] {
          return (value.toLowerCase().match(/[a-z0-9]+/g) || [])
            .filter(term => term.length > 2 && !HELP_STOP_WORDS.has(term));
        }

        function helpTopicScore(
          terms: readonly string[],
          topic: PortalCraftHelpTopic
        ): number {
          const title = `${topic.documentTitle} ${topic.title}`.toLowerCase();
          const summary = topic.summary.toLowerCase();
          return terms.reduce((score, term) => {
            if (title.includes(term)) return score + 3;
            if (summary.includes(term)) return score + 1;
            return score;
          }, 0);
        }

        export function findPortalCraftHelpTopic(
          topicIdOrQuestion: string
        ): PortalCraftHelpTopic | undefined {
          const normalized = topicIdOrQuestion.trim().toLowerCase();
          if (SAFE_HELP_TOPIC_ID.test(normalized)) {
            const exact = portalCraftHelpTopics.find(topic => topic.id === normalized);
            if (exact) return exact;
          }
          const terms = helpTerms(topicIdOrQuestion);
          if (terms.length === 0) return undefined;
          return portalCraftHelpTopics
            .map(topic => ({ topic, score: helpTopicScore(terms, topic) }))
            .filter(item => item.score > 0)
            .sort((left, right) => right.score - left.score)[0]?.topic;
        }

        export function answerPortalCraftHelpTopic(
          topicIdOrQuestion: string
        ): string {
          const topic = findPortalCraftHelpTopic(topicIdOrQuestion);
          if (!topic) {
            return "No verified help-document topic matched that question.";
          }
          const citation = topic.sourceUrl
            ? `[${topic.sourceTitle}](${topic.sourceUrl})`
            : `${topic.sourceTitle} (${topic.repositoryPath})`;
          return [
            `**${topic.documentTitle} — ${topic.title}**`,
            topic.summary,
            "",
            `Source: ${citation}`,
          ].join("\n");
        }
        """;
    }

    private static IReadOnlyList<object> BuildHelpTopics(
        IReadOnlyList<RepositoryDocument> documents)
    {
        var topics = new List<object>();
        var usedIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var document in documents)
        {
            var sections = document.Sections.Count > 0
                ? document.Sections
                : [new RepositoryDocumentSection("Overview", document.Summary)];
            foreach (var section in sections)
            {
                var baseId = ToSlug($"{document.Title}-{section.Title}");
                var id = baseId;
                var suffix = 2;
                while (!usedIds.Add(id))
                {
                    id = $"{baseId}-{suffix}";
                    suffix += 1;
                }
                topics.Add(new
                {
                    id,
                    section.Title,
                    documentTitle = document.Title,
                    section.Summary,
                    sourceTitle = document.SourceTitle ?? document.Title,
                    document.SourceUrl,
                    repositoryPath = document.Path
                });
            }
        }
        return topics;
    }

    private static string BuildClientPanel() =>
        """
        import { portalCraftGeneratedQueries } from "./portalCraft.generated";

        type Props = {
          assistantName?: string;
          onAsk: (prompt: string) => void;
        };

        export function PortalCraftGeneratedPanel({
          assistantName = "PortalCraft AI",
          onAsk,
        }: Props) {
          return (
            <aside aria-label={assistantName}>
              <h2>{assistantName}</h2>
              <p>Repository-discovered, read-only query starters</p>
              <div>
                {portalCraftGeneratedQueries.map(query => (
                  <button key={query.id} type="button" onClick={() => onAsk(query.prompt)}>
                    {query.prompt}
                  </button>
                ))}
              </div>
            </aside>
          );
        }
        """;

    private static string BuildReadme(RepositoryProfile profile) =>
        $$"""
        # Generated PortalCraft AI onboarding

        The repository tool discovered:

        - {{profile.ApiOperations.Count}} API operations
        - {{profile.ApiOperations.Count(operation => operation.ReadOnly)}} read-only API operations
        - {{profile.UiRoutes.Count}} UI routes
        - {{profile.QueryCandidates.Count}} query candidates

        ## Integration

        1. Review `portalcraft-ai.manifest.json`; remove false positives and add product-owned authorization requirements.
        2. Copy `server/PortalCraftGeneratedCatalog.cs` into the ASP.NET Core project and call
           `app.MapPortalCraftGeneratedCatalog()`.
        3. Copy the generated client files into the React application.
        4. Use `portalCraftAssistant.generated.ts` to resolve reviewed in-portal search and
           validator destinations instead of hard-coding product routes.
        5. Connect `onAsk` to the product's governed PortalCraft AI chat endpoint.
        6. Implement typed handlers for approved operations. The generator never exposes write operations automatically.

        Generated files are scaffolding, not an authorization boundary. Product APIs must continue to enforce
        authentication, authorization, validation, audit, and data classification.

        ## Preview

        From the PortalCraft AI source repository:

        `dotnet run --project tools/PortalCraft.RepoTool -- serve "{{profile.Repository}}/.portalcraft-ai"`
        """;

    private static string BuildDashboard(RepositoryProfile profile)
    {
        var data = JsonSerializer.Serialize(profile, JsonOptions)
            .Replace("</", "<\\/", StringComparison.Ordinal);
        return $$"""
        <!doctype html>
        <html lang="en">
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <title>PortalCraft AI repository dashboard</title>
          <style>
            :root { font-family: Segoe UI, Arial, sans-serif; color: #172033; background: #eef3f8; }
            body { margin: 0; }
            header { padding: 22px 30px; color: white; background: #172033; }
            header h1 { margin: 0 0 5px; }
            header p { margin: 0; color: #c9d6e5; }
            main { padding: 26px 30px 50px; }
            .metrics { display: grid; grid-template-columns: repeat(4, minmax(150px, 1fr)); gap: 14px; }
            .card, section { border: 1px solid #d7dee8; border-radius: 12px; background: white; box-shadow: 0 3px 12px #1720330d; }
            .card { padding: 18px; }
            .card span { display: block; color: #5b6879; font-size: 13px; }
            .card strong { display: block; margin-top: 8px; font-size: 30px; }
            section { margin-top: 20px; padding: 20px; overflow-x: auto; }
            h2 { margin: 0 0 15px; }
            table { width: 100%; border-collapse: collapse; font-size: 13px; }
            th, td { padding: 10px; border-bottom: 1px solid #edf1f5; text-align: left; vertical-align: top; }
            th { color: #526173; }
            code { color: #005a9e; }
            .safe { color: #107c10; font-weight: 700; }
            .blocked { color: #a4262c; font-weight: 700; }
            @media (max-width: 800px) { .metrics { grid-template-columns: repeat(2, 1fr); } main { padding: 18px; } }
          </style>
        </head>
        <body>
          <header>
            <h1>PortalCraft AI repository dashboard</h1>
            <p id="repository"></p>
          </header>
          <main>
            <div class="metrics" id="metrics"></div>
            <section>
              <h2>Suggested read-only queries</h2>
              <table><thead><tr><th>Prompt</th><th>Operation</th><th>View</th><th>Parameters</th></tr></thead><tbody id="queries"></tbody></table>
            </section>
            <section>
              <h2>Discovered API operations</h2>
              <table><thead><tr><th>Method</th><th>Route</th><th>Classification</th><th>Source</th></tr></thead><tbody id="operations"></tbody></table>
            </section>
            <section>
              <h2>Discovered UI routes</h2>
              <table><thead><tr><th>Route</th><th>Source</th></tr></thead><tbody id="routes"></tbody></table>
            </section>
          </main>
          <script>
            const data = {{data}};
            const escapeHtml = value => String(value ?? "").replace(/[&<>"']/g, character => ({
              "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;"
            })[character]);
            document.getElementById("repository").textContent = data.repository;
            const metrics = [
              ["API operations", data.apiOperations.length],
              ["Read-only operations", data.apiOperations.filter(item => item.readOnly).length],
              ["UI routes", data.uiRoutes.length],
              ["Query candidates", data.queryCandidates.length]
            ];
            document.getElementById("metrics").innerHTML = metrics
              .map(([label, value]) => `<div class="card"><span>${escapeHtml(label)}</span><strong>${value}</strong></div>`)
              .join("");
            document.getElementById("queries").innerHTML = data.queryCandidates
              .map(item => `<tr><td>${escapeHtml(item.prompt)}</td><td><code>${escapeHtml(item.operationId)}</code></td><td>${escapeHtml(item.viewPath || "Review required")}</td><td>${escapeHtml(item.parameters.join(", ") || "None")}</td></tr>`)
              .join("");
            document.getElementById("operations").innerHTML = data.apiOperations
              .map(item => `<tr><td>${escapeHtml(item.method)}</td><td><code>${escapeHtml(item.route)}</code></td><td class="${item.readOnly ? "safe" : "blocked"}">${item.readOnly ? "Read-only candidate" : "Excluded mutation"}</td><td>${escapeHtml(item.source)}</td></tr>`)
              .join("");
            document.getElementById("routes").innerHTML = data.uiRoutes
              .map(item => `<tr><td><code>${escapeHtml(item.path)}</code></td><td>${escapeHtml(item.source)}</td></tr>`)
              .join("");
          </script>
        </body>
        </html>
        """;
    }

    private static string Escape(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string NullableString(string? value) =>
        value is null ? "null" : $"\"{Escape(value)}\"";

    private static IReadOnlyList<string> GetRouteTags(string route) =>
        Words(route)
            .Select(word => word.ToLowerInvariant())
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToArray();

    private static string ToSlug(string value)
    {
        var words = Words(value)
            .SelectMany(word => System.Text.RegularExpressions.Regex
                .Matches(word.ToLowerInvariant(), "[a-z0-9]+")
                .Cast<System.Text.RegularExpressions.Match>()
                .Select(match => match.Value))
            .Where(word => word.Length > 0)
            .Take(18)
            .ToArray();
        var slug = string.Join("-", words);
        if (slug.Length == 0)
        {
            return "help-topic";
        }
        return slug.Length <= 150 ? slug : slug[..150].TrimEnd('-');
    }

    private static IEnumerable<string> Words(string value) =>
        System.Text.RegularExpressions.Regex
            .Replace(value, "([a-z0-9])([A-Z])", "$1 $2")
            .Split(['/', '-', '_', ' '], StringSplitOptions.RemoveEmptyEntries);
}
