using System.Diagnostics;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace PortalCraft.RepoTool;

public sealed partial class RepositoryKnowledgeBuilder
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
    };

    private static readonly string[] ExcludedDirectories =
    [
        ".git",
        ".github",
        ".portalcraft-ai",
        "bin",
        "build",
        "dist",
        "node_modules",
        "obj"
    ];

    public RepositoryKnowledge Build(
        string repository,
        string? requestedBranch,
        int sinceDays,
        int limit,
        IReadOnlyList<string>? manualPaths = null)
    {
        var report = new PullRequestScenarioAnalyzer().Analyze(
            repository,
            requestedBranch,
            sinceDays,
            limit);
        var documents = ReadDocumentation(repository, manualPaths);
        var warnings = report.Warnings.ToList();
        if (documents.Count == 0)
        {
            warnings.Add(manualPaths?.Count > 0
                ? "No Markdown help manuals were found in the selected paths."
                : "No repository Markdown documentation was found.");
        }

        return new(
            ResolveRepositoryName(report.Repository),
            report.Branch,
            DateTimeOffset.UtcNow,
            documents,
            report.Changes.Select(change => new RepositoryChangeInsight(
                change.Commit,
                change.PullRequestNumber,
                ClassifyChange(change.Title),
                change.Title,
                change.MergedAt,
                change.ChangedFiles.Take(12).ToArray())).ToArray(),
            warnings);
    }

    public IReadOnlyList<string> Write(
        RepositoryKnowledge knowledge,
        string outputDirectory,
        bool force)
    {
        var output = Path.GetFullPath(outputDirectory);
        if (Directory.Exists(output)
            && Directory.EnumerateFileSystemEntries(output).Any()
            && !force)
        {
            throw new InvalidOperationException(
                $"Output directory is not empty: {output}. Pass --force to replace generated files.");
        }

        Directory.CreateDirectory(output);
        var json = Path.Combine(output, "repository-knowledge.json");
        var markdown = Path.Combine(output, "repository-knowledge.md");
        var typescript = Path.Combine(output, "portalCraftKnowledge.generated.ts");
        var serialized = JsonSerializer.Serialize(knowledge, JsonOptions);
        File.WriteAllText(json, serialized);
        File.WriteAllText(markdown, BuildMarkdown(knowledge));
        File.WriteAllText(
            typescript,
            $"// Generated by PortalCraft.RepoTool. Review before integrating.{Environment.NewLine}" +
            $"export const portalCraftRepositoryKnowledge = {serialized} as const;{Environment.NewLine}");
        return [json, markdown, typescript];
    }

    public static IReadOnlyList<RepositoryDocument> ReadDocumentation(
        string repository,
        IReadOnlyList<string>? manualPaths = null)
    {
        var root = Path.GetFullPath(repository);
        if (!Directory.Exists(root))
        {
            throw new DirectoryNotFoundException($"Repository directory does not exist: {root}");
        }

        var files = manualPaths?.Count > 0
            ? ResolveManualFiles(root, manualPaths)
            : Directory.EnumerateFiles(root, "*.md", SearchOption.AllDirectories);
        return files
            .Where(path => !ContainsExcludedDirectory(root, path))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(path => DocumentationRank(root, path))
            .ThenBy(path => path, StringComparer.OrdinalIgnoreCase)
            .Take(40)
            .Select(path => ReadDocument(root, path))
            .Where(document => document is not null)
            .Cast<RepositoryDocument>()
            .ToArray();
    }

    private static IEnumerable<string> ResolveManualFiles(
        string root,
        IReadOnlyList<string> manualPaths)
    {
        foreach (var manualPath in manualPaths)
        {
            var candidate = Path.GetFullPath(Path.Combine(root, manualPath));
            var relative = Path.GetRelativePath(root, candidate);
            if (relative.Equals("..", StringComparison.Ordinal)
                || relative.StartsWith($"..{Path.DirectorySeparatorChar}", StringComparison.Ordinal)
                || Path.IsPathRooted(relative))
            {
                throw new ArgumentException(
                    $"Help manual path must stay inside the repository: {manualPath}");
            }

            if (File.Exists(candidate))
            {
                if (!Path.GetExtension(candidate).Equals(".md", StringComparison.OrdinalIgnoreCase))
                {
                    throw new ArgumentException(
                        $"Help manual files must use the .md extension: {manualPath}");
                }
                yield return candidate;
                continue;
            }

            if (Directory.Exists(candidate))
            {
                foreach (var file in Directory.EnumerateFiles(
                    candidate,
                    "*.md",
                    SearchOption.AllDirectories))
                {
                    yield return file;
                }
                continue;
            }

            throw new FileNotFoundException(
                $"Help manual path does not exist: {manualPath}",
                candidate);
        }
    }

    public static string ClassifyChange(string title)
    {
        if (SecurityWords().IsMatch(title))
        {
            return "security";
        }
        if (BugFixWords().IsMatch(title))
        {
            return "bugFix";
        }
        if (EnhancementWords().IsMatch(title))
        {
            return "enhancement";
        }
        return "change";
    }

    private static RepositoryDocument? ReadDocument(string root, string path)
    {
        string content;
        try
        {
            content = File.ReadAllText(path);
        }
        catch (IOException)
        {
            return null;
        }
        catch (UnauthorizedAccessException)
        {
            return null;
        }

        var lines = content
            .Split(['\r', '\n'], StringSplitOptions.RemoveEmptyEntries)
            .Select(line => line.Trim())
            .Where(line => line.Length > 0)
            .ToArray();
        var title = lines.FirstOrDefault(line => line.StartsWith('#'))
            ?.TrimStart('#', ' ')
            ?? Path.GetFileNameWithoutExtension(path);
        var summaryLines = lines
            .Where(line => !line.StartsWith('#')
                && !line.StartsWith("```")
                && !line.StartsWith('|')
                && !line.StartsWith("---"))
            .Take(6);
        var summary = CollapseWhitespace().Replace(string.Join(" ", summaryLines), " ").Trim();
        if (summary.Length == 0)
        {
            return null;
        }
        if (summary.Length > 700)
        {
            summary = $"{summary[..697]}...";
        }

        return new(
            Path.GetRelativePath(root, path).Replace('\\', '/'),
            title.Length <= 160 ? title : title[..160],
            summary);
    }

    private static bool ContainsExcludedDirectory(string root, string path)
    {
        var relative = Path.GetRelativePath(root, path);
        var segments = relative.Split(
            [Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar],
            StringSplitOptions.RemoveEmptyEntries);
        return segments.Any(segment => ExcludedDirectories.Contains(
            segment,
            StringComparer.OrdinalIgnoreCase));
    }

    private static int DocumentationRank(string root, string path)
    {
        var relative = Path.GetRelativePath(root, path).Replace('\\', '/');
        if (relative.Equals("README.md", StringComparison.OrdinalIgnoreCase))
        {
            return 0;
        }
        if (relative.StartsWith("docs/", StringComparison.OrdinalIgnoreCase)
            || relative.Contains("/docs/", StringComparison.OrdinalIgnoreCase))
        {
            return 1;
        }
        if (Path.GetFileName(path).Equals("README.md", StringComparison.OrdinalIgnoreCase))
        {
            return 2;
        }
        return 3;
    }

    private static string ResolveRepositoryName(string root)
    {
        var startInfo = new ProcessStartInfo("git")
        {
            WorkingDirectory = root,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            CreateNoWindow = true
        };
        startInfo.ArgumentList.Add("config");
        startInfo.ArgumentList.Add("--get");
        startInfo.ArgumentList.Add("remote.origin.url");
        using var process = Process.Start(startInfo);
        if (process is not null)
        {
            var remote = process.StandardOutput.ReadToEnd().Trim();
            process.WaitForExit();
            if (process.ExitCode == 0 && remote.Length > 0)
            {
                var normalized = remote.Replace('\\', '/').TrimEnd('/');
                var name = normalized[(normalized.LastIndexOf('/') + 1)..];
                if (name.EndsWith(".git", StringComparison.OrdinalIgnoreCase))
                {
                    name = name[..^4];
                }
                if (name.Length > 0)
                {
                    return name;
                }
            }
        }

        return Path.GetFileName(root.TrimEnd(
            Path.DirectorySeparatorChar,
            Path.AltDirectorySeparatorChar));
    }

    private static string BuildMarkdown(RepositoryKnowledge knowledge)
    {
        var documents = knowledge.Documents.Count == 0
            ? "- No Markdown documentation found."
            : string.Join(
                Environment.NewLine,
                knowledge.Documents.Select(document =>
                    $"- `{document.Path}` — **{document.Title}**: {document.Summary}"));
        var changes = knowledge.Changes.Count == 0
            ? "- No recent changes found."
            : string.Join(
                Environment.NewLine,
                knowledge.Changes.Select(change =>
                    $"- `{change.Commit[..8]}` [{change.Category}] {change.Title}"));

        return $"""
            # PortalCraft repository knowledge

            Repository: `{knowledge.Repository}`

            Branch: `{knowledge.Branch}`

            Generated: `{knowledge.GeneratedAt:O}`

            ## Application documentation

            {documents}

            ## Recent fixes and enhancements

            {changes}

            ## Integration guidance

            Use the generated TypeScript module as a reviewed, build-time knowledge source.
            Keep product authorization and live business-data queries in product-owned APIs.
            Regenerate this package after meaningful documentation or branch changes.
            """;
    }

    [GeneratedRegex(
        @"\b(auth|authorization|permission|role|security|token|access)\b",
        RegexOptions.IgnoreCase)]
    private static partial Regex SecurityWords();

    [GeneratedRegex(
        @"\b(fix|fixed|bug|correct|prevent|resolve|repair|handle|retain|restore)\b",
        RegexOptions.IgnoreCase)]
    private static partial Regex BugFixWords();

    [GeneratedRegex(
        @"\b(add|added|enable|enhance|improve|introduce|expand|support|create|allow)\b",
        RegexOptions.IgnoreCase)]
    private static partial Regex EnhancementWords();

    [GeneratedRegex(@"\s+")]
    private static partial Regex CollapseWhitespace();
}
