using System.Text.Json;

namespace ContextIq.RepoTool;

public sealed class IntegrationGenerator
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
    };

    public GenerationResult Generate(
        RepositoryProfile profile,
        string outputDirectory,
        bool force = false)
    {
        var output = Path.GetFullPath(outputDirectory);
        if (Directory.Exists(output)
            && Directory.EnumerateFileSystemEntries(output).Any()
            && !force)
        {
            throw new InvalidOperationException(
                $"Output directory is not empty: {output}. Pass --force to replace generated files.");
        }

        Directory.CreateDirectory(output);
        var files = new List<string>();
        Write(
            output,
            "context-iq.manifest.json",
            JsonSerializer.Serialize(profile, JsonOptions),
            files);
        Write(output, "server/ContextIqGeneratedCatalog.cs", BuildServerCatalog(profile), files);
        Write(output, "client/contextIq.generated.ts", BuildClientCatalog(profile), files);
        Write(output, "client/ContextIqGeneratedPanel.tsx", BuildClientPanel(), files);
        Write(output, "README.md", BuildReadme(profile), files);
        return new(profile, output, files);
    }

    private static void Write(
        string output,
        string relativePath,
        string content,
        ICollection<string> files)
    {
        var path = Path.Combine(output, relativePath.Replace('/', Path.DirectorySeparatorChar));
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, content);
        files.Add(path);
    }

    private static string BuildServerCatalog(RepositoryProfile profile)
    {
        var queries = string.Join(
            $",{Environment.NewLine}",
            profile.QueryCandidates.Select(candidate =>
                $"        new(\"{Escape(candidate.Id)}\", \"{Escape(candidate.Prompt)}\", " +
                $"\"{Escape(candidate.OperationId)}\", {NullableString(candidate.ViewPath)})"));

        return $$"""
            // Generated by ContextIq.RepoTool. Review before integrating.
            using Microsoft.AspNetCore.Builder;
            using Microsoft.AspNetCore.Http;
            using Microsoft.AspNetCore.Routing;

            namespace ContextIq.Generated;

            public sealed record ContextIqGeneratedQuery(
                string Id,
                string Prompt,
                string OperationId,
                string? ViewPath);

            public static class ContextIqGeneratedCatalog
            {
                public static readonly IReadOnlyList<ContextIqGeneratedQuery> Queries =
                [
            {{queries}}
                ];

                public static IEndpointRouteBuilder MapContextIqGeneratedCatalog(
                    this IEndpointRouteBuilder endpoints)
                {
                    endpoints.MapGet("/api/context-iq/catalog", () => Results.Ok(Queries));
                    return endpoints;
                }
            }
            """;
    }

    private static string BuildClientCatalog(RepositoryProfile profile) =>
        $$"""
        // Generated by ContextIq.RepoTool. Review before integrating.
        export type ContextIqGeneratedQuery = {
          id: string;
          prompt: string;
          operationId: string;
          viewPath?: string;
        };

        export const contextIqGeneratedQueries = {{JsonSerializer.Serialize(profile.QueryCandidates, JsonOptions)}} as const;
        """;

    private static string BuildClientPanel() =>
        """
        import { contextIqGeneratedQueries } from "./contextIq.generated";

        type Props = {
          assistantName?: string;
          onAsk: (prompt: string) => void;
        };

        export function ContextIqGeneratedPanel({
          assistantName = "Context IQ",
          onAsk,
        }: Props) {
          return (
            <aside aria-label={assistantName}>
              <h2>{assistantName}</h2>
              <p>Repository-discovered, read-only query starters</p>
              <div>
                {contextIqGeneratedQueries.map(query => (
                  <button key={query.id} type="button" onClick={() => onAsk(query.prompt)}>
                    {query.prompt}
                  </button>
                ))}
              </div>
            </aside>
          );
        }
        """;

    private static string BuildReadme(RepositoryProfile profile) =>
        $$"""
        # Generated Context IQ onboarding

        The repository tool discovered:

        - {{profile.ApiOperations.Count}} API operations
        - {{profile.ApiOperations.Count(operation => operation.ReadOnly)}} read-only API operations
        - {{profile.UiRoutes.Count}} UI routes
        - {{profile.QueryCandidates.Count}} query candidates

        ## Integration

        1. Review `context-iq.manifest.json`; remove false positives and add product-owned authorization requirements.
        2. Copy `server/ContextIqGeneratedCatalog.cs` into the ASP.NET Core project and call
           `app.MapContextIqGeneratedCatalog()`.
        3. Copy the generated client files into the React application.
        4. Connect `onAsk` to the product's governed Context IQ chat endpoint.
        5. Implement typed handlers for approved operations. The generator never exposes write operations automatically.

        Generated files are scaffolding, not an authorization boundary. Product APIs must continue to enforce
        authentication, authorization, validation, audit, and data classification.
        """;

    private static string Escape(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string NullableString(string? value) =>
        value is null ? "null" : $"\"{Escape(value)}\"";
}
